# Generated by Django 5.2.4 on 2025-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_students_material_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to='core.course'),
        ),
    ]
